spring:
  datasource:
    username: root
    password: czc123
    url: jdbc:mysql:///mybatis_plus

logging:
  level:
    com.example: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted       # ????????????,?????????????????
#                                         ??????????????@TableLogic??
      logic-delete-value: 1             # ?????
      logic-not-delete-value: 0         # ?????



